# EcoEvolutionSim Configuration

# Simulation
n_agents = 1_000
world_size = 50.0
cell_size = 5.0
steps_per_frame = 2

# Movement
strategy = "RANDOM_WALK" # options: RANDOM_WALK, LANGEVIN, CORRELATED_RW, ACTIVE_BROWNIAN
base_speed = 0.1

# ecology / interaction
r_interact = 1.0